apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla
  namespace: scylla
spec:
  agentVersion: 3.4.0@sha256:441403aed8880cad1feef68aa7a8ee9ffd99a458dc1dcff3dc54ce5bf3cb07b7
  version: 6.1.4
  automaticOrphanedNodeCleanup: true
  alternator:
    servingCertificate:
      type: UserManaged
      userManagedOptions:
        secretName: scylla-alternator-local-serving-certs
  datacenter:
    name: us-east1
    racks:
      - name: us-east1-b
        members: 1
        scyllaConfig: scylla-config
        storage:
          capacity: 100Gi
          storageClassName: premium-rwo   # <-- Change to match your storage class
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 3000m
            memory: 12Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east1-b
          tolerations:
            - key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
              effect: NoSchedule
      - name: us-east1-c
        members: 1
        storage:
          capacity: 100Gi
          storageClassName: premium-rwo   # <-- Change to match your storage class
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 3000m
            memory: 12Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east1-c
          tolerations:
            - key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
              effect: NoSchedule
      - name: us-east1-d
        members: 1
        storage:
          capacity: 100Gi
          storageClassName: premium-rwo   # <-- Change to match your storage class
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 3000m
            memory: 12Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east1-d
          tolerations:
            - key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
              effect: NoSchedule
