apiVersion: v1
kind: Pod
metadata:
  name: scylla-client
  labels:
    app: scylla-client
spec:
  restartPolicy: Always
  containers:
    - name: scylla-client
      image: docker.io/scylladb/scylla:6.1.4
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity

